### PR TITLE
[WIP] Image widget from stginga PR

### PR DESCRIPTION
**Pull request by pllim**
Moved from spacetelescope/stginga#158

TODO:
- [ ] Implement the rest of commented stuff in the notebook.
- [ ] Implement https://github.com/eteq/astrowidgets/pull/1#issuecomment-405069040

### CODE REVIEW

**Comment by mwcraig** [comment]
These are my notes from the sprint Saturday night:

```python
# Define a callback that shows the output of a print
out = ipyw.Output()

def show_event(viewer, event, datax, datay):
    with out:
       # print(dir(event))
        print(event.data_x, event.data_y)
display(out)

# This would work for adding markers with the appropriate callback
gvc = w._viewer.get_canvas()
gvc.add_callback('cursor-down', show_event)

# Changing binds for pan/zoom
bind_map = w._viewer.get_bindmap()

# ms is click-drag
# kp is keypress
# sc is scroll
# map_event args: mode, modifiers (usually empty), trigger, event_name (last two as strings)
bind_map.map_event(None, (), 'ms_left', 'pan')

# contrast with right mouse
bind_map.map_event(None, (), 'ms_right', 'contrast')

# zoom by scrolling
bind_map.map_event(None, (), 'pa_pan', 'zoom')

# pan by scrolling
bind_map.map_event(None, (), 'pa_pan', 'pan')

# restore contrast with ctrl-right-click... NOTE TUPLE FOR MODIFIER
bind_map.map_event(None, ('ctrl',), 'ms_right', 'contrast_restore')

# click to center
bind_map.map_event(None, ('shift',), 'ms_left', 'panset')

# to bind a custom event to a function of your choosing

bind_map.map_event(None, (), 'kp_w', 'my_custom_event')

# Signature of callback_function is
def callback_function(viewer, event, data_x, data_y, *args):
    with out:
        print('The magic key was pressed')
    pass

# prefix for keypress is keydown-
# suffix for ms_... is -down
# suffix for sc_... is -scroll
w._viewer.set_callback('keydown-my_custom_event', callback_function)
```

**Comment by pllim** [comment]
@eteq , need to clarify the specs for "remove some but not all markers" as well. Only 3 methods left unimplemented (I think).

**Comment by pllim** [comment]
Note for future: To get the best out of this implementation...

* Use https://github.com/ejeschke/aggdraw/tree/vectorized-drawing
* Use `Circles` object from Ginga (not available yet)

**Comment by pllim** [comment]
So, I finally moved from Windows 7 and Windows 10 😅 and found that the following Windows instructions in the notebook needs updating:

* The `vectorized-drawing` branch is also good for non-Windows, actually, but only if the lag is really bothering you.
* Hacking aggdraw and installing it from source is still needed for Windows 10 (see https://github.com/ejeschke/ginga/issues/664#issuecomment-408704038).
* `conda install -c conda-forge nodejs` no longer gives an error, thus manual install of `nodejs` and `yarn` are no longer necessary.

**Comment by mwcraig** [comment]
I'm going to merge this....about to drop a bunch of package template stuff into the repo, seems like it will be cleaner with this merged in.

**Comment by mwcraig** [comment]
Will open an issue for some of the to-do stuff....

**Comment by eteq** [comment]
yeah, I should have mentioned you should feel free to do that, so sounds good @mwcraig 😉

**Pull request merged**
